package Vista;

import Modelo.TextPrompt;
import Modelo.mod_Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frm_calificacion extends javax.swing.JFrame {

    private TextPrompt tp;
    DefaultTableModel dtm = new DefaultTableModel();

    public frm_calificacion() {

        initComponents();

        //array para poner encabezados a columnas en el  jtable
        String[] titulo = new String[]{"CODIGO", "NOMBRE", "APELLIDOS                                    ", "MATERIA", "NOTA 1", "NOTA 2", "NOTA 3", "15%", "35%", "50%", "NOTA FINAL", "CALIFICACION"};
        dtm.setColumnIdentifiers(titulo);
        tbl_lista.setModel(dtm);
        // poner placeholder
        TextPrompt cod = new TextPrompt("Solo Introducir para busquedas", tx_cod);

    }

    //////////////////////////////////////////////////////////////////////////////////////////
    //lista de calificaciones
    public void actualizar_lista() {
        mod_Conexion modc = new mod_Conexion();
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        con = modc.getConexion();
        //consulta
        String sql = "select Codigo,Nombre,Apellido,Materia,Nota1,Nota2,Nota3,Notap1,Notap2,Notap3,NotaFinal,Calificacion  from calificacion";
        try {

            //consulta de insercion de datos
            ps = con.prepareStatement(sql);
            //ejecutar consulta
            rs = ps.executeQuery();
            while (rs.next()) {
                dtm.addRow(new Object[]{
                    rs.getString("Codigo"),
                    rs.getString("Nombre"),
                    rs.getString("Apellido"),
                    rs.getString("Materia"),
                    rs.getString("Nota1"),
                    rs.getString("Nota2"),
                    rs.getString("Nota3"),
                    rs.getString("Notap1"),
                    rs.getString("Notap2"),
                    rs.getString("Notap3"),
                    rs.getString("NotaFinal"),
                    rs.getString("Calificacion")
                });//fin nuevo objeto  
            }
            //cerrar base de datos
            con.close();
        }//fin try
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de eliminacion: " + e);
        }//fin catch
    }
    //////////////////////////////////////////////////////////////////////////////////////////
    //limpiar lista

    public void lim_list() {
        int cont = tbl_lista.getRowCount();
        while (cont >= 1) {
            cont--;
            dtm.removeRow(cont);
        }

    }

    /////////////////////////////////////////////////////////////////////////////////////////
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_eli2 = new javax.swing.JButton();
        pnl_calificacion = new javax.swing.JTabbedPane();
        pnl_calificar = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        tx_cod = new javax.swing.JTextField();
        tx_ape = new javax.swing.JTextField();
        tx_nom = new javax.swing.JTextField();
        tx_n1 = new javax.swing.JTextField();
        tx_n2 = new javax.swing.JTextField();
        tx_n3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tx_np1 = new javax.swing.JTextField();
        tx_np2 = new javax.swing.JTextField();
        tx_np3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tx_cal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tx_npf = new javax.swing.JTextField();
        btn_mod = new javax.swing.JButton();
        btn_gua = new javax.swing.JButton();
        btn_bus = new javax.swing.JButton();
        btn_eli = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        tx_mat = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btn_lim = new javax.swing.JButton();
        btn_cali = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        pnl_lista = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_lista = new javax.swing.JTable();
        btn_act = new javax.swing.JButton();

        btn_eli2.setBackground(new java.awt.Color(51, 0, 204));
        btn_eli2.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btn_eli2.setForeground(new java.awt.Color(255, 255, 255));
        btn_eli2.setText("Eliminar");
        btn_eli2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102)));
        btn_eli2.setBorderPainted(false);
        btn_eli2.setMargin(new java.awt.Insets(10, 10, 10, 10));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnl_calificacion.setBackground(new java.awt.Color(0, 0, 153));
        pnl_calificacion.setPreferredSize(new java.awt.Dimension(860, 560));

        pnl_calificar.setBackground(new java.awt.Color(204, 255, 255));
        pnl_calificar.setForeground(new java.awt.Color(0, 0, 102));
        pnl_calificar.setMinimumSize(new java.awt.Dimension(850, 560));
        pnl_calificar.setPreferredSize(new java.awt.Dimension(850, 560));

        jSeparator1.setBackground(new java.awt.Color(51, 0, 204));

        jLabel3.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Codigo:");

        jLabel4.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Apellido:");

        jLabel6.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Nota 1:");

        jLabel7.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Nota 2:");

        jLabel8.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Nota 3:");

        jSeparator3.setBackground(new java.awt.Color(51, 0, 204));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 153));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(3, 0));

        tx_cod.setBackground(new java.awt.Color(255, 255, 255));
        tx_cod.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tx_cod.setForeground(new java.awt.Color(0, 0, 102));
        tx_cod.setBorder(null);
        tx_cod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tx_codKeyTyped(evt);
            }
        });

        tx_ape.setBackground(new java.awt.Color(255, 255, 255));
        tx_ape.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tx_ape.setForeground(new java.awt.Color(0, 0, 102));
        tx_ape.setBorder(null);

        tx_nom.setBackground(new java.awt.Color(255, 255, 255));
        tx_nom.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tx_nom.setForeground(new java.awt.Color(0, 0, 102));
        tx_nom.setBorder(null);

        tx_n1.setBackground(new java.awt.Color(255, 255, 255));
        tx_n1.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tx_n1.setForeground(new java.awt.Color(0, 0, 102));
        tx_n1.setBorder(null);
        tx_n1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tx_n1KeyTyped(evt);
            }
        });

        tx_n2.setBackground(new java.awt.Color(255, 255, 255));
        tx_n2.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tx_n2.setForeground(new java.awt.Color(0, 0, 102));
        tx_n2.setBorder(null);
        tx_n2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tx_n2KeyTyped(evt);
            }
        });

        tx_n3.setBackground(new java.awt.Color(255, 255, 255));
        tx_n3.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tx_n3.setForeground(new java.awt.Color(0, 0, 102));
        tx_n3.setBorder(null);
        tx_n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_n3ActionPerformed(evt);
            }
        });
        tx_n3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tx_n3KeyTyped(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 0, 204));

        jLabel1.setFont(new java.awt.Font("Harrington", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("-CALIFICACIONES-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("-Calificacion Final-");

        jLabel10.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Nota 1:");

        jLabel11.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Nota 2:");

        jLabel12.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Nota 3:");

        tx_np1.setEditable(false);
        tx_np1.setBackground(new java.awt.Color(255, 255, 255));
        tx_np1.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tx_np1.setForeground(new java.awt.Color(0, 0, 102));
        tx_np1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tx_np1.setBorder(null);
        tx_np1.setEnabled(false);

        tx_np2.setEditable(false);
        tx_np2.setBackground(new java.awt.Color(255, 255, 255));
        tx_np2.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tx_np2.setForeground(new java.awt.Color(0, 0, 102));
        tx_np2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tx_np2.setBorder(null);
        tx_np2.setEnabled(false);

        tx_np3.setEditable(false);
        tx_np3.setBackground(new java.awt.Color(255, 255, 255));
        tx_np3.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tx_np3.setForeground(new java.awt.Color(0, 0, 102));
        tx_np3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tx_np3.setBorder(null);
        tx_np3.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Calificacion");

        tx_cal.setEditable(false);
        tx_cal.setBackground(new java.awt.Color(255, 255, 255));
        tx_cal.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tx_cal.setForeground(new java.awt.Color(0, 0, 102));
        tx_cal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tx_cal.setBorder(null);
        tx_cal.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("-Notas Porcentuales-");

        jLabel15.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Nota Final:");

        tx_npf.setEditable(false);
        tx_npf.setBackground(new java.awt.Color(255, 255, 255));
        tx_npf.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tx_npf.setForeground(new java.awt.Color(0, 0, 102));
        tx_npf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tx_npf.setBorder(null);
        tx_npf.setEnabled(false);

        btn_mod.setBackground(new java.awt.Color(51, 0, 204));
        btn_mod.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btn_mod.setForeground(new java.awt.Color(255, 255, 255));
        btn_mod.setText("Modificar");
        btn_mod.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102)));
        btn_mod.setBorderPainted(false);
        btn_mod.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modActionPerformed(evt);
            }
        });

        btn_gua.setBackground(new java.awt.Color(51, 0, 204));
        btn_gua.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btn_gua.setForeground(new java.awt.Color(255, 255, 255));
        btn_gua.setText("Guardar");
        btn_gua.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102)));
        btn_gua.setBorderPainted(false);
        btn_gua.setMargin(new java.awt.Insets(10, 10, 10, 10));

        btn_bus.setBackground(new java.awt.Color(51, 0, 204));
        btn_bus.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btn_bus.setForeground(new java.awt.Color(255, 255, 255));
        btn_bus.setText("Buscar");
        btn_bus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102)));
        btn_bus.setBorderPainted(false);
        btn_bus.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btn_bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_busActionPerformed(evt);
            }
        });

        btn_eli.setBackground(new java.awt.Color(51, 0, 204));
        btn_eli.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btn_eli.setForeground(new java.awt.Color(255, 255, 255));
        btn_eli.setText("Eliminar");
        btn_eli.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102)));
        btn_eli.setBorderPainted(false);
        btn_eli.setMargin(new java.awt.Insets(10, 10, 10, 10));

        jLabel31.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 102));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("Materia:");

        tx_mat.setBackground(new java.awt.Color(255, 255, 255));
        tx_mat.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tx_mat.setForeground(new java.awt.Color(0, 0, 102));
        tx_mat.setBorder(null);

        jLabel16.setForeground(new java.awt.Color(102, 204, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("-Las busquedas deben realizarse por Codigo-");

        btn_lim.setBackground(new java.awt.Color(51, 0, 204));
        btn_lim.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btn_lim.setForeground(new java.awt.Color(255, 255, 255));
        btn_lim.setText("Limpiar");
        btn_lim.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102)));
        btn_lim.setBorderPainted(false);
        btn_lim.setMargin(new java.awt.Insets(10, 10, 10, 10));

        btn_cali.setBackground(new java.awt.Color(51, 0, 204));
        btn_cali.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btn_cali.setForeground(new java.awt.Color(255, 255, 255));
        btn_cali.setText("Calificar");
        btn_cali.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102)));
        btn_cali.setBorderPainted(false);
        btn_cali.setMargin(new java.awt.Insets(10, 10, 10, 10));

        jLabel17.setForeground(new java.awt.Color(102, 204, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("-Solo se cargan los valores al pulsar Calificar -");

        jLabel18.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 102));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("%");

        jLabel19.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 102));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("%");

        jLabel20.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 102));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("%");

        javax.swing.GroupLayout pnl_calificarLayout = new javax.swing.GroupLayout(pnl_calificar);
        pnl_calificar.setLayout(pnl_calificarLayout);
        pnl_calificarLayout.setHorizontalGroup(
            pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_calificarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_calificarLayout.createSequentialGroup()
                        .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnl_calificarLayout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tx_ape, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnl_calificarLayout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tx_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnl_calificarLayout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tx_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnl_calificarLayout.createSequentialGroup()
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tx_mat, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_calificarLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tx_n1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_calificarLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tx_n2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_calificarLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tx_n3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(24, 24, 24)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_calificarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_gua, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_eli, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_calificarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_lim, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cali, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_calificarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_calificarLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tx_cal, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_calificarLayout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_calificarLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(100, 100, 100))))
                    .addGroup(pnl_calificarLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnl_calificarLayout.createSequentialGroup()
                                .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnl_calificarLayout.createSequentialGroup()
                                        .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tx_np3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tx_np2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tx_np1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel18)))
                                    .addComponent(tx_npf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel14))
                        .addContainerGap())))
            .addGroup(pnl_calificarLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        pnl_calificarLayout.setVerticalGroup(
            pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_calificarLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_calificarLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_calificarLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(tx_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(tx_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(tx_ape, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel31)
                                    .addComponent(tx_mat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(tx_n1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(tx_n2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(tx_n3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(33, 33, 33)
                                .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_gua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_eli, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_lim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_cali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnl_calificarLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addGap(27, 27, 27)
                                .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_calificarLayout.createSequentialGroup()
                                        .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10)
                                            .addComponent(tx_np1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(tx_np2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12)
                                            .addComponent(tx_np3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnl_calificarLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel19)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel20)))
                                .addGap(18, 18, 18)
                                .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(tx_npf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addGroup(pnl_calificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(tx_cal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_calificarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))))
        );

        pnl_calificacion.addTab("Calificaciones", pnl_calificar);

        pnl_lista.setBackground(new java.awt.Color(204, 255, 255));
        pnl_lista.setPreferredSize(new java.awt.Dimension(850, 560));

        jSeparator2.setBackground(new java.awt.Color(51, 0, 204));

        jPanel2.setBackground(new java.awt.Color(51, 0, 204));

        jLabel2.setFont(new java.awt.Font("Harrington", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-LISTADO-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tbl_lista.setBackground(new java.awt.Color(204, 255, 255));
        tbl_lista.setFont(new java.awt.Font("Bernard MT Condensed", 0, 12)); // NOI18N
        tbl_lista.setForeground(new java.awt.Color(0, 0, 102));
        tbl_lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "Materia", "Nota 1", "Nota 2", "Nota 3", "15%", "35%", "50%", "Nota Final", "Calificacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_lista);

        btn_act.setBackground(new java.awt.Color(51, 0, 204));
        btn_act.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btn_act.setForeground(new java.awt.Color(255, 255, 255));
        btn_act.setText("Actualizar");
        btn_act.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102)));
        btn_act.setBorderPainted(false);
        btn_act.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btn_act.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_listaLayout = new javax.swing.GroupLayout(pnl_lista);
        pnl_lista.setLayout(pnl_listaLayout);
        pnl_listaLayout.setHorizontalGroup(
            pnl_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_listaLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_listaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
                    .addGroup(pnl_listaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_act, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_listaLayout.setVerticalGroup(
            pnl_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_listaLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_act, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pnl_calificacion.addTab("Lista", pnl_lista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_calificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_calificacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_modActionPerformed

    private void btn_busActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_busActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_busActionPerformed

    private void tx_n1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_n1KeyTyped
        // solo aceptar numeros con punto
        int key = evt.getKeyChar();

        if (key >= 48 && key <= 57 || key == 46) {
            if (key == 46)//limitar ingreso a un solo punto
            {
                String dato = tx_n1.getText();
                int tama = dato.length();
                for (int i = 0; i <= tama; i++) {
                    if (dato.contains(".")) {
                        evt.setKeyChar((char) java.awt.event.KeyEvent.VK_CLEAR);
                    }

                }
            }
        } else {
            evt.setKeyChar((char) java.awt.event.KeyEvent.VK_CLEAR);
            evt.consume();
        }
    }//GEN-LAST:event_tx_n1KeyTyped

    private void tx_n2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_n2KeyTyped
        // solo aceptar numeros con punto
        int key = evt.getKeyChar();

        if (key >= 48 && key <= 57 || key == 46) {
            if (key == 46)//limitar ingreso a un solo punto
            {
                String dato = tx_n2.getText();
                int tama = dato.length();
                for (int i = 0; i <= tama; i++) {
                    if (dato.contains(".")) {
                        evt.setKeyChar((char) java.awt.event.KeyEvent.VK_CLEAR);
                    }

                }
            }
        } else {
            evt.setKeyChar((char) java.awt.event.KeyEvent.VK_CLEAR);
            evt.consume();
        }    }//GEN-LAST:event_tx_n2KeyTyped

    private void tx_n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_n3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_n3ActionPerformed

    private void tx_n3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_n3KeyTyped
        // solo aceptar numeros con punto
        int key = evt.getKeyChar();

        if (key >= 48 && key <= 57 || key == 46) {
            if (key == 46)//limitar ingreso a un solo punto
            {
                String dato = tx_n3.getText();
                int tama = dato.length();
                for (int i = 0; i <= tama; i++) {
                    if (dato.contains(".")) {
                        evt.setKeyChar((char) java.awt.event.KeyEvent.VK_CLEAR);
                    }

                }
            }
        } else {
            evt.setKeyChar((char) java.awt.event.KeyEvent.VK_CLEAR);
            evt.consume();
        }
    }//GEN-LAST:event_tx_n3KeyTyped

    private void tx_codKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_codKeyTyped
        // solo aceptar numeros sin punto
        int key = evt.getKeyChar();

        boolean num = key >= 48 && key <= 57;

        if (!num) {
            evt.consume();
        }

        if (tx_cod.getText().length() >= 4) {
            evt.consume();
        }
    }//GEN-LAST:event_tx_codKeyTyped

    private void btn_actActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_actActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_calificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_calificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_calificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_calificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_calificacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_act;
    public javax.swing.JButton btn_bus;
    public javax.swing.JButton btn_cali;
    public javax.swing.JButton btn_eli;
    public javax.swing.JButton btn_eli2;
    public javax.swing.JButton btn_gua;
    public javax.swing.JButton btn_lim;
    public javax.swing.JButton btn_mod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane pnl_calificacion;
    private javax.swing.JPanel pnl_calificar;
    private javax.swing.JPanel pnl_lista;
    public javax.swing.JTable tbl_lista;
    public javax.swing.JTextField tx_ape;
    public javax.swing.JTextField tx_cal;
    public javax.swing.JTextField tx_cod;
    public javax.swing.JTextField tx_mat;
    public javax.swing.JTextField tx_n1;
    public javax.swing.JTextField tx_n2;
    public javax.swing.JTextField tx_n3;
    public javax.swing.JTextField tx_nom;
    public javax.swing.JTextField tx_np1;
    public javax.swing.JTextField tx_np2;
    public javax.swing.JTextField tx_np3;
    public javax.swing.JTextField tx_npf;
    // End of variables declaration//GEN-END:variables
}
